import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity/visual-editing";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import { SanityLive } from "@/sanity/lib/live";

export const metadata: Metadata = {
  title: "Coastal Electrical",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        {children}

        <Toaster richColors closeButton />
        <SanityLive />

        {(await draftMode()).isEnabled && (
          <>
            <VisualEditing />
          </>
        )}
      </body>
    </html>
  );
}
